spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companies-test
    username: admin-test
    password: super-secret-test
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
