spring:
  datasource:
    url: jdbc:postgresql://localhost:5234/companies-test
    username: adminTest
    password: superSecretTest
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
